Revert "Hack getopts to allow arbitrary placement of positional arguments."
This reverts commit 69d69eaaa4196cee9cc199619988c51894baff5f.

diff --git a/host-bin/unmount-chroot b/host-bin/unmount-chroot
--- a/host-bin/unmount-chroot
+++ b/host-bin/unmount-chroot
@@ -38,24 +38,29 @@ Options:
     -y          Signal any remaining processes without confirmation.
                 Automatically escalates from SIGTERM to SIGKILL."
 
-# Common functions
-. "$BINDIR/../installer/functions"
+# Function to exit with exit code $1, spitting out message $@ to stderr
+error() {
+    local ecode="$1"
+    shift
+    echo "$*" 1>&2
+    exit "$ecode"
+}
 
 # Process arguments
-getopts_string='ac:fkpt:xy'
-while getopts_nextarg; do
-    case "$getopts_var" in
+while getopts 'ac:fkpt:xy' f; do
+    case "$f" in
     a) ALLCHROOTS='y';;
-    c) CHROOTS="`readlink -m "$getopts_arg"`";;
+    c) CHROOTS="`readlink -m "$OPTARG"`";;
     f) FORCE='y';;
     k) SIGNAL="KILL";;
     p) PRINT='y';;
-    t) TRIES="$getopts_arg";;
+    t) TRIES="$OPTARG";;
     x) EXCLUDEROOT='y';;
     y) YES='a';;
     \?) error 2 "$USAGE";;
     esac
 done
+shift "$((OPTIND-1))"
 
 # Need at least one chroot listed, or -a; not both.
 if [ $# = 0 -a -z "$ALLCHROOTS" ] || [ ! $# = 0 -a -n "$ALLCHROOTS" ]; then
